#ifndef HELLO_WORLD_COMMON_H
#define HELLO_WORLD_COMMON_H

#include "sdkconfig.h"

#define IT_WIFI_SSID CONFIG_SSID
#define IT_WIFI_PASS CONFIG_PASS
#define WIFI_STA_CONNECTED_BIT BIT1
#define WIFI_STA_DISCONNECTED_BIT BIT2

#endif //HELLO_WORLD_COMMON_H
