#ifndef HELLO_WORLD_COMMON_H
#define HELLO_WORLD_COMMON_H

#include "sdkconfig.h"

#define IT_WIFI_SSID CONFIG_WIFI_SSID
#define IT_WIFI_PASS CONFIG_WIFI_PASS
#define IT_RF_GPIO CONFIG_RF_TRANSMITTER_DATA_GPIO
#define IT_QUEUE_SIZE CONFIG_MQTT_QUEUE_SIZE
#define WIFI_STA_CONNECTED_BIT BIT1
#define WIFI_STA_DISCONNECTED_BIT BIT2

#endif //HELLO_WORLD_COMMON_H
