#ifndef RF_BRIDGE_COMMON_H
#define RF_BRIDGE_COMMON_H

#include "sdkconfig.h"

#define IT_WIFI_SSID CONFIG_WIFI_SSID
#define IT_WIFI_PASS CONFIG_WIFI_PASS
#define IT_RF_GPIO CONFIG_RF_TRANSMITTER_DATA_GPIO
#define IT_QUEUE_SIZE CONFIG_MQTT_QUEUE_SIZE
#define IT_MQTT_HOST CONFIG_MQTT_HOST
#define IT_MQTT_TOPIC CONFIG_MQTT_TOPIC
#define WIFI_STA_CONNECTED_BIT BIT1
#define WIFI_STA_DISCONNECTED_BIT BIT2

#endif //RF_BRIDGE_COMMON_H
